name = "vestaboard-tube"
main = "src/index.js"
compatibility_date = "2025-05-06"

[triggers]
crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "STATE"
id = "f10a27d4b8bc4840afc169dc72fe9fe0"

[vars]
GITHUB_RAW_BASE = "https://raw.githubusercontent.com/JDAS89/vestaboard-tube/main"
